# **LINEAR OPTIMIZATION FINAL PROJECT**

# **ROBUST SHORTEST TIME DELIVERY PATHS**

<p align="justify">
The Assurance Delivery company is a startup company specializing in package delivery within the western areas of the United States. They advertise guaranteed delivery within a specified time. Their quoted times are not always shorter than other delivery companies, but delivery comes with a money-back guarantee if, for any reason, the delivery is not met on time. The company necessarily has a vested interest in finding delivery routes that are not only efficient (short) but robust (not likely to incur delays). In order to set their rates,the company is seeking a method for finding an optimal route between two given locations.

<p align="justify">
The problem of finding a shortest path between two locations can be easily solved as an integer program, provided that the number of possible routes is not too large. Also,the problem of finding the route least likely to incur a delay is similarly solved. Assurance
Delivery would like to solve the problem of a compromise route that helps then maintain competitiveness without significant reduction in promised delivery time.

<p align="justify">
You are given the following tasks:
<p align="justify">
1. Use the provided network data to solve the shortest path problem for user-supplied starting and ending locations. Ignore any possible delays.
<p align="justify">
2. Use the provided network data to solve the minimum delay likelihood problem for user-supplied starting and ending locations. Ignore travel times.
<p align="justify">
3. Combine the two previous solution methods where the objective is to minimize the weighted sum of travel time and delay likelihood. The relative weight should be an adjustable parameter. Determine a reasonable relative weighting based on experiments you perform.
<p align="justify">
4. Solve the combined problem using your weight selection with starting city A and ending locations at every other city. Report your findings and make recommendations to the company.

<p align="justify">
The data set is provided as two files distance.csv and delay.csv which are commadelimited 15 x 15 arrays. The entry in the ith row and jth column of the respective arrays gives the distance (or delay probability) between city i and city j. If an array has entry zero,
this indicates that the cities are not connected by a path.
<p align="justify">
The networks we will consider are symmetric - distances and delays do not depend on the direction of travel.

# **Modelling the problem**

---




Let $x_{ij}$ be a binary decision variable where:

$x_{ij} = 1$ if the path from city $i$ to city $j$ is included in the travel from city $A$ to city $O$ , and
$x_{ij} = 0$ otherwise.

The objective function to minimize is the total distance of the path:

\begin{equation}
\text{Minimize} \sum_{i,j} d_{ij} \cdot x_{ij}
\end{equation}

Subject to the following constraints:

Ensure that there is zero or one outgoing edge from each inner city(except for A, O):

\begin{equation}
\sum_{j} x_{ij} = y_{j} \quad \text{for} \quad i \in \{B, C, D, E, F, G, H, I, J, K, L, M, N\}
\end{equation}

Ensure that there is zero or one incoming edge to each inner city (except for A, O):

\begin{equation}
\sum_{i} x_{ij} = y_{i} \quad \text{for} \quad j \in \{B, C, D, E, F, G, H, I, J, K, L, M, N\}
\end{equation}

where $y_{j}  \in \{0, 1\}$, and $y_{i}  \in \{0, 1\}$. Note that although it seems we used different notations for the number of outgoing and incoming edges from a city, they ( $y_{j}$ and $y_{i}$) are the same numbers for the same city. For example, if the number of outgoing edges from city $B$ ($j=B$) is $y_{B}$, so is that of incoming edges to city $B$ ($i = B$), which means $y_{j}$ and $y_{i}$ are the same numbers for the same city.


Ensure that the destination city has exactly zero outgoing edges:

\begin{equation}
\sum_{j} x_{Oj} = 1 \quad \text{for} \quad j \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}
\end{equation}

Ensure that the starting city has exactly zero incoming edges:

\begin{equation}
\sum_{i} x_{iA} = 0 \quad \text{for} \quad i \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}
\end{equation}

Ensure that the destination city has exactly one incoming edge:

\begin{equation}
\sum_{i} x_{iO} = 1 \quad \text{for} \quad i \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}
\end{equation}

Ensure that the starting city has exactly one outgoing edge:

\begin{equation}
\sum_{j} x_{Aj} = 0 \quad \text{for} \quad j \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}
\end{equation}

$x_{ij}$, $y_{i}  \in \{0, 1\}$,  $\quad \forall i,j \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}$

These constraints ensure that:

- There is exactly one path from the starting city to the destination city.
- There are no cycles in the path.
- Each city (excluding the starting and destination cities) may not necessarily be visited exactly once.

Solving this linear programming problem will give us the shortest path between the given cities both in terms of distances and likelikood of delays.



# **Receiving and reading the data**

In [ ]:
from numpy import genfromtxt
my_distances = genfromtxt('distance.csv', delimiter=',')
my_delays = genfromtxt('delay.csv', delimiter=',')
print(my_distances)
# print(my_delays)

[[ 0.  0.  0. 42.  0.  0.  0. 59. 29.  0.  0. 25.  0.  0.  0.]
 [ 0.  0.  0.  8. 21.  0.  0.  0.  0.  0. 25.  0.  0.  0. 25.]
 [ 0.  0.  0.  0.  0.  0. 31. 62.  0. 11.  0.  0. 40.  0.  0.]
 [42.  8.  0.  0. 28.  0.  0.  0. 42.  0. 29. 40.  0.  0.  0.]
 [ 0. 21.  0. 28.  0.  0.  0.  0.  0.  0.  0. 62. 65.  0. 26.]
 [ 0.  0.  0.  0.  0.  0. 25. 10. 28.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 31.  0.  0. 25.  0. 32. 41.  0. 50.  0. 54.  0.  0.]
 [59.  0. 62.  0.  0. 10. 32.  0. 35. 73.  0.  0.  0.  0.  0.]
 [29.  0.  0. 42.  0. 28. 41. 35.  0.  0. 46.  0.  0.  0.  0.]
 [ 0.  0. 11.  0.  0.  0.  0. 73.  0.  0.  0.  0. 40.  0.  0.]
 [ 0. 25.  0. 29.  0.  0. 50.  0. 46.  0.  0.  0. 40.  9. 13.]
 [25.  0.  0. 40. 62.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 40.  0. 65.  0. 54.  0.  0. 40. 40.  0.  0. 33. 40.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  9.  0. 33.  0.  9.]
 [ 0. 25.  0.  0. 26.  0.  0.  0.  0.  0. 13.  0. 40.  9.  0.]]


# **Creating the constraints**

In [10]:
import numpy as np
from itertools import combinations

# List of cities
# cities = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'][:4]
cities = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O']
start_city = cities[0]
destination_city = cities[-1]

# Distance between cities (replace with actual distances)
# distances = my_distances[:4, :4]
distances = my_distances
delays = my_delays
# distances[1, 3] = 6
# distances[3, 1] = 6

# Find the maximum distance
max_distance = np.max(distances)
# Update main diagonal elements
np.fill_diagonal(distances, max_distance + 1)
print("distances:")
print(distances)

# Number of cities
num_cities = len(cities)

# Inequality Constraints:

# Constraint coefficients for exactly zero or one outgoing edge from each inner city(except for A, O)
A_outgoing = []
b_outgoing = []
for i_index, i in enumerate(cities[1:-1]):  # Exclude the last city
    # print(i_index, i)
    row = np.zeros(num_cities ** 2)
    rhs_binary = np.zeros(num_cities-2) # to count # of outgoing edges from each inner cities, B, C, ..., N.
    rhs_binary[i_index] = -1 # outgoing = incoming, so same rhs binaries
    for j in cities:
        if j != i and distances[cities.index(i), cities.index(j)] > 0:
            j_index = cities.index(j)
            row[num_cities * cities.index(i) + cities.index(j)] = 1
    row = np.concatenate((row, rhs_binary))
    A_outgoing.append(row)
    b_outgoing.append(0)
# print("A_outgoing:")
# print(np.array(A_outgoing))

# Constraint coefficients for exactly zero or one incoming edge from each inner city(except for A, O)
A_incoming = []
b_incoming = []

for j_index, j in enumerate(cities[1:-1]):  # Exclude the last city
    row = np.zeros(num_cities ** 2)
    rhs_binary = np.zeros(num_cities-2) # to count # of incoming edges from each inner cities, B, C, ..., N.
    rhs_binary[j_index] = -1 # outgoing = incoming, so same rhs binaries
    for i_index, i in enumerate(cities):
        if i != j and distances[cities.index(i), cities.index(j)] > 0:
            row[num_cities * cities.index(i) + cities.index(j)] = 1
    row = np.concatenate((row, rhs_binary))
    A_incoming.append(row)
    b_incoming.append(0)
# print("A_incoming:")
# print(np.array(A_incoming))

A = np.vstack((A_outgoing, A_incoming))
b = np.concatenate((b_outgoing, b_incoming))
print("\nInequality Constraints (A):")
print(np.array(A))
print("\nInquality Bounds (b):")
print(np.array(b))

# Equality Constraints
A_eq = []
b_eq = []

# Destination city constraint for having 0 outgoing edges
row = np.zeros(num_cities ** 2)
rhs_binary = np.zeros(num_cities-2)
for j in cities:
    if distances[cities.index(destination_city), cities.index(j)] > 0:
        row[num_cities * cities.index(destination_city) + cities.index(j)] = 1
row = np.concatenate((row, rhs_binary))
A_eq.append(row)
b_eq.append(0)
# print("A_eq:")
# print(np.array(A_eq))


# Starting city constraint for having zero incoming edges
row = np.zeros(num_cities ** 2)
rhs_binary = np.zeros(num_cities-2)
for i in cities:
    if distances[cities.index(i), cities.index(start_city)] > 0:
        row[num_cities * cities.index(i) + cities.index(start_city)] = 1
row = np.concatenate((row, rhs_binary))
A_eq.append(row)
b_eq.append(0)
# print("A_eq:")
# print(np.array(A_eq))

# Destination city constraint for having 1 incoming edge
row = np.zeros(num_cities ** 2)
rhs_binary = np.zeros(num_cities-2)
for i in cities:
    if distances[cities.index(i), cities.index(destination_city)] > 0:
        row[num_cities * cities.index(i) + cities.index(destination_city)] = 1
row = np.concatenate((row, rhs_binary))
A_eq.append(row)
b_eq.append(1)
# print("A_eq:")
# print(np.array(A_eq))

# Starting city constraint for having 1 outgoing edge
row = np.zeros(num_cities ** 2)
rhs_binary = np.zeros(num_cities-2)
for j in cities:
    if distances[cities.index(start_city), cities.index(j)] > 0:
        row[num_cities * cities.index(start_city) + cities.index(j)] = 1
row = np.concatenate((row, rhs_binary))
A_eq.append(row)
b_eq.append(1)
# print("A_eq:")
# print(np.array(A_eq))


print("\nEquality Constraints (A_eq):")
print(np.array(A_eq))
print("\nEquality Bounds (b_eq):")
print(np.array(b_eq))
print("A_eq.shape: ", np.array(A_eq).shape)
print("A.shape: ", np.array(A).shape)

distances:
[[76.  0.  0. 42.  0.  0.  0. 59. 29.  0.  0. 25.  0.  0.  0.]
 [ 0. 76.  0.  8. 21.  0.  0.  0.  0.  0. 25.  0.  0.  0. 25.]
 [ 0.  0. 76.  0.  0.  0. 31. 62.  0. 11.  0.  0. 40.  0.  0.]
 [42.  8.  0. 76. 28.  0.  0.  0. 42.  0. 29. 40.  0.  0.  0.]
 [ 0. 21.  0. 28. 76.  0.  0.  0.  0.  0.  0. 62. 65.  0. 26.]
 [ 0.  0.  0.  0.  0. 76. 25. 10. 28.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 31.  0.  0. 25. 76. 32. 41.  0. 50.  0. 54.  0.  0.]
 [59.  0. 62.  0.  0. 10. 32. 76. 35. 73.  0.  0.  0.  0.  0.]
 [29.  0.  0. 42.  0. 28. 41. 35. 76.  0. 46.  0.  0.  0.  0.]
 [ 0.  0. 11.  0.  0.  0.  0. 73.  0. 76.  0.  0. 40.  0.  0.]
 [ 0. 25.  0. 29.  0.  0. 50.  0. 46.  0. 76.  0. 40.  9. 13.]
 [25.  0.  0. 40. 62.  0.  0.  0.  0.  0.  0. 76.  0.  0.  0.]
 [ 0.  0. 40.  0. 65.  0. 54.  0.  0. 40. 40.  0. 76. 33. 40.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  9.  0. 33. 76.  9.]
 [ 0. 25.  0.  0. 26.  0.  0.  0.  0.  0. 13.  0. 40.  9. 76.]]

Inequality Constraints (A):
[[ 0.  0.  0. 

# **Solve the IP problem**

In [11]:
"""
All decision variables Xij, Yi are binaries from {0, 1}:
"""

import pandas as pd
import numpy as np
import scipy.optimize as opt

# The problem we will solve is:

# min z  =  dAA*xAA +  dAB*xAB + ... + dOA*xOA + ...+ dOO*xOO + 0*yB + 0*yC + ... + 0*yN

# s.t.    Ae x = be

#          xAA, xAB, ... ,  xOO, yB, yC, ..., yN in {0, 1}


# First build the objective vector ( matrix dij of distances from city i to j).
d = distances.flatten()
rhs_binary = np.zeros(num_cities-2)
d = np.concatenate((d, rhs_binary))
average_d = d/np.mean(d)
# print("distances: ")
# print(distances)
# print("\nObjective average_d :")
# print(average_d)
# print("d.shape = ", d.shape)

p = delays.flatten()
rhs_binary = np.zeros(num_cities-2)
p = np.concatenate((p, rhs_binary))
average_p = p/np.mean(p)
# print("\nObjective average_p :")
# print(average_p)
# print("p.shape = ", p.shape)

# beta = float(input("beta = "))

# d = d + beta*p


# Next, create the coefficient array for the inequality constraints.
# Note that the inequalities must be Ax <= b, so some sign
# changes result when converting >= into <=.
A_ineq = None # if no inequality constraints


# Next the right-hand-side vector for the inequalities
# Sign changes can occur here too.
b_ineq = None # if no inequality constraints



#The coefficient matrix for the equality constraints and
# the right hand side vector.
# Ae = None # if no equality constraints
Ae = np.vstack((A, A_eq))
be = np.concatenate((b, b_eq))
# print(Ae)
# print(be)
print("Ae.shape = ", Ae.shape)
print("be.shape = ", be.shape)

# be = None # if no equality constraints

# Next, we provide any lower and upper bound vectors, one
# value for each decision variable.  In this example all
# lower bound are zero and there are no upper bounds.
bounds = [(0, 1) for _ in range(num_cities**2 + num_cities - 2)] # considering added rhs_binary variables
# print("bounds.shape = ", bounds.shape )

# Lastly, we can specify which variables are required to be integer.
# If no variables are integer then isint=[];  In our example, only x2
# is integer.
# isint = np.ones(num_cities + num_cities - 2)
isint = [1 for _ in range(num_cities**2 + num_cities - 2)]
# print("isint.shape = ", isint.shape)

# The call to the mixed integer solver looks like the following.
# Notice that we pass usual "c" when we have a minimization
# problem, we send "-c" when we have max problem.
# This is because the solver is expecting a minimization.

res=opt.linprog(d, A_ineq, b_ineq, Ae, be, bounds, integrality = isint)

# The result is stored in the dictionary variable "res".
# In particular, to show the optimal objective value and the
# optimal decision variable values:

print("min z = ", res['fun'])
print("at optimal solution x = ")
print(res['x'])

Ae.shape =  (30, 238)
be.shape =  (30,)
min z =  75.0
at optimal solution x = 
[ 0.  0.  0.  1.  0.  0.  0.  0. -0.  0.  0. -0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0. 

# **Printing the solution path**

In [12]:
# Given data
objecvtive_value = res['fun']
solution = np.array(res['x'])
print("Optimal path in binary matrix form:")
print(res['x'][:num_cities**2].reshape(num_cities, num_cities))
# solution = np.array([0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])
# d = np.array([43., 0., 0., 42., 0., 0., 43., 0., 6., 21., 0., 0., 43., 0., 0., 42., 6., 0., 43., 28., 0., 21., 0., 28., 43.])

# Execute the code
if any(solution):
    print("\nOptimal path:")
    path = [start_city]  # Start from city 'A'
    path_distance = []
    next_city_index = 0  # Start from the first city in the solution vector
    while path[-1] != destination_city:  # Continue until we reach the destination city 'E'
        # Find the index of the next city with a value of 1 in the solution vector
        solution_slice = solution[next_city_index * len(cities): (next_city_index + 1) * len(cities)]
        destination_slice = d[next_city_index * len(cities): (next_city_index + 1) * len(cities)]
        next_city_index = np.where(solution_slice == 1)[0][0]

        # print(np.dot(solution_slice, destination_slice))
        dist = str(np.dot(solution_slice, destination_slice))
        path_distance.append(dist)

        # Convert the index to the corresponding city label
        next_city = cities[next_city_index]
        path.append(next_city)

    # Print the optimal path
    print(' --> '.join(path))
    print(' + '.join(path_distance), f' = {objecvtive_value}')
else:
    print("No solution found.")


Optimal path in binary matrix form:
[[ 0.  0.  0.  1.  0.  0.  0.  0. -0.  0.  0. -0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

Optimal path:
A -

# **Importing Your Own Python Module or Python File into Colab**

Resourse: [Resourse](https://medium.com/analytics-vidhya/importing-your-own-python-module-or-python-file-into-colab-3e365f0a35ec)

https://medium.com/analytics-vidhya/importing-your-own-python-module-or-python-file-into-colab-3e365f0a35ec

In [ ]:
# Step 1: Mount your google drive in google colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Xulosa: ipynb larni insert qilgan bilan import qilib bo'lmas ekan. Import qilish uchu, file .py kengyatmasi bilan bo'lishi shart ekan. Demak, shu import qimoqchi file ni .py ko'rinishida saqlab, colabga upload qilib shu, step 1,2,3 larni qilish kk.

In [ ]:
# Step 2: Insert the directory
# import sys
# sys.path.insert(0,'/content/drive/MyDrive/Colab Notebooks/simplex.ipynb')

above steps did not work, so new way approach
[resourse](https://stackoverflow.com/questions/62590523/how-to-import-models-in-google-colab-which-is-saved-in-a-folder)
and for some tasks:
https://stackoverflow.com/questions/60706752/how-to-make-directory-on-the-google-colab

In [ ]:
# Step 2: Insert the directory
import sys
sys.path.insert(0,'/content/drive/MyDrive/Colab Notebooks/simplexx.py')

In [ ]:
# Step 3: Import the file.py here as you want:
import simplexx
print(simplexx.solve_LP())

8


Yuqoridagi step1, step 2, step3 lar faqat file.py insert qilinib, faqat file.py import qilinsagina ishlarkan! Katta rahmat!

In [ ]:
!mkdir models

mkdir: cannot create directory ‘models’: File exists


In [ ]:
!mv 'simplexx.py' 'models'

mv: cannot stat 'simplexx.py': No such file or directory


In [ ]:
# To download:
# !sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic
# !jupyter nbconvert --to pdf /content/project_all_in_one.ipynb